#!/bin/bash

#-----------
# Configurations
#-----------

TARBALL_BASE_DIR=${TARBALL_BASE_DIR-/var/apps}
TARBALL_NAME=${TARBALL_NAME}
TARBALL_EXTRACT_NAME=${TARBALL_EXTRACT_NAME-$TARBALL_NAME}
TARBALL_FILENAME=${TARBALL_FILENAME}

TARBALL_APP_DIR=${TARBALL_BASE_DIR}/${TARBALL_NAME}

#-----------
# Install Script
#-----------

if [[ -e $TARBALL_APP_DIR ]]; then
  echo "$TARBALL_NAME already deployed to $TARBALL_BASE_DIR."
else
  echo "Creating $TARBALL_NAME ($TARBALL_BASE_DIR)..."
  mkdir -p $TARBALL_BASE_DIR
  (cd $TARBALL_BASE_DIR && tar zxf $TARBALL_FILENAME)

  if [[ ! -e $TARBALL_APP_DIR ]]; then
    mv $TARBALL_BASE_DIR/$TARBALL_EXTRACT_NAME $TARBALL_BASE_DIR/$TARBALL_NAME
  fi
  echo "DONE Creating $TARBALL_NAME ($TARBALL_BASE_DIR)..."
fi
