#!/bin/bash
[[ -z "$INFO_LEVEL" ]] && source ./bits/bootstrap/logging

#-----------
# Configurations
#-----------

TARBALL_BASE_DIR=${TARBALL_BASE_DIR-/var/local/apps}
TARBALL_NAME=${TARBALL_NAME}
TARBALL_EXTRACT_NAME=${TARBALL_EXTRACT_NAME-$TARBALL_NAME}
TARBALL_FILENAME=${TARBALL_FILENAME}

TARBALL_APP_DIR=${TARBALL_BASE_DIR}/${TARBALL_NAME}
TARBALL_FULL_FILENAME=$(pwd)/$TARBALL_FILENAME

#-----------
# Install Script
#-----------

if [[ "`which unzip`" == "" ]]; then
  apt-get install -y unzip
fi

if [[ -e $TARBALL_APP_DIR ]]; then
  debug "$TARBALL_NAME already deployed to $TARBALL_APP_DIR."
else
  notify "Creating $TARBALL_NAME ($TARBALL_BASE_DIR)..."
  mkdir -p $TARBALL_BASE_DIR
  (cd $TARBALL_BASE_DIR && tar zxf $TARBALL_FULL_FILENAME)
  debug "DONE Creating $TARBALL_NAME ($TARBALL_BASE_DIR)"
fi
